### ISSUE TITLE
Travis-CI -> Github Actions

### ISSUE THREAD

**Issue by bmorris3** [exoclime/THOR#48]
Travis-CI has changed their pricing structure making unlimited free builds of the repo no longer available.

The best option may be to migrate the travis-ci testing tools here to GitHub Actions, which is an analogous service. 

Would @deitrr or @nabajour be able to give me a quick verdict on whether or not it would be useful to update to GitHub Actions? Are the test results still useful?

Related/Links:
* [Github Actions Migration guide](https://docs.github.com/en/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions)
* astropy [PR](https://github.com/astropy/astropy/pull/10388) migrating from travis-ci to github actions

**Comment by deitrr** [comment]
Thanks for looking out, @bmorris3. Yes, I find the build test very useful, and I hope I can expand on this to include actual code testing. So migration is probably worthwhile. Let me know if you prefer me to attempt this myself or if you need input from me.

**Comment by bmorris3** [comment]
I've implemented the Github actions migration for you 🎉 

From now on, you'll be able to see the history of builds for each commit [here](https://github.com/exoclime/THOR/actions). 

If you browse around within that webpage you'll be able to explore the logs from stdout for each iteration of the compile test, see [here](https://github.com/exoclime/THOR/runs/1784008978?check_suite_focus=true#step:3:373) for an example of a successful build.

I've also updated the status badge in the README to report the status from GitHub Actions rather than Travis.

**Comment by bmorris3** [comment]
Also FYI – if you need to edit the build config, the file is [here](https://github.com/exoclime/THOR/blob/main/.github/workflows/test_compile.yml).

**Comment by deitrr** [comment]
Beautiful, thank you @bmorris3. Should I remove the travis.yml file?

**Comment by bmorris3** [comment]
Yep, good idea!

**Comment by nabajour** [comment]
That's great, thanks @bmorris3!
